
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo Docker username is $DOCKER_USERNAME
      - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t mdnurakmal/aws_pipeline:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push mdnurakmal/aws_pipeline:latest